### ISSUE TITLE
Show present and absent inputs next to each other 

### ISSUE THREAD

**Issue by range-of-motion** [Super45coders/Student-attendance#1]
You're currently showing them underneath each other, but using flex or grid you could easily show them next to each other. It makes it much easier to use that way, and you're wasting less space.

```html
<div class="grid">
  <div>
    <span>Your inputs for presence go here</span>
  </div>
  <div>
    <span>Your inputs for absence go here</span>
  </div>
</div>
```

```css
.grid {
  display: grid;
  grid-template-columns: auto auto;
}
```
